screen:
  height: 775
  width: 1165
scene:
  height: 2000
  width: 3000
  depth: 2700
  depth-old: 3150
  origin: [-1490, -1100, 3000]
  crop: [-1450, 1450, -1100, 1500]
  decimation: 5
min_energy: 60
max_energy: 200
max_speed: 5
max_dist_cluster: 80
max_height: 1400
min_height: 300
radius_level: 80
weight:
  g: 0.004
  min: 0.1
  max: 0.1
thresh_jump: 10
cluster:
  epsilon: 500
  fill: true
  min_samples: 180
  crop: [200, 200, 300]
  clustInClust: false
colors:
  energy: [255,20,20]
  background: [21,23,26]
  point_cloud: [100, 100, 100]
  ground_truth: [100, 100, 100]
ripples:
  max_age: 80
  speed: 3
  delay: 10
  aging: 1
  number: 5
display_cluster: false
simulation:
  activate: false
  clusters: 3
  Npoints: 100
  max_height: 1300
  min_height: 800
  display_ground_truth: false
  jump:
    probability: 0.02
    height: 50
    speed: 2
